#!/usr/bin/env python3
"""Cross-repo sync for the get-shipped orchestrator.

Walks every sibling repo in ../, and reports what changed since this
orchestrator last looked (state/last-sync). Pull-based: sibling repos never
need to know this repo exists. Sources of truth, in order:
  1. git (commits, branches, dirty/unpushed state)
  2. the newest tmp/wrapups/*.yaml in each sibling (the per-repo handoff)
  3. open PRs on GitHub (only with --prs; needs network + gh)

Usage:
  scripts/sync.py            print the delta + status to stdout
  scripts/sync.py --write    also rewrite STATUS.md and stamp state/last-sync
  scripts/sync.py --prs      include open PRs (slower, network)
  scripts/sync.py --repo X   only repo X
"""
import argparse, datetime as dt, json, os, re, subprocess, sys
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
ROOT = HERE.parent
STAMP = HERE / "state" / "last-sync"
STATUS = HERE / "STATUS.md"
PRIORITIES = HERE / "PRIORITIES.md"
PROJECTS = HERE / "state" / "projects.json"
HISTORY = HERE / "state" / "history.json"
DATA = HERE / "docs" / "data.json"
SELF = HERE.name


def git(repo, *args):
    try:
        return subprocess.run(["git", "-C", str(repo), *args], capture_output=True, text=True, timeout=30).stdout.strip()
    except Exception:
        return ""


def load_projects():
    return json.loads(PROJECTS.read_text())["repos"] if PROJECTS.exists() else {}


def priority_order():
    """{repo: (rank, hands_off)} from state/projects.json."""
    return {k: (v.get("rank") or 999, bool(v.get("hands_off"))) for k, v in load_projects().items()}


def parse_wrapup(path):
    """Tolerant top-level YAML key extraction (no pyyaml dependency)."""
    keys, cur = {}, None
    for line in path.read_text(errors="replace").splitlines():
        m = re.match(r"^([A-Za-z_][\w\-]*):\s*(.*)$", line)
        if m:
            cur = m.group(1)
            keys[cur] = [m.group(2)] if m.group(2) not in ("", ">", "|", ">-", "|-") else []
        elif cur is not None:
            keys[cur].append(line)

    def scalar(k):
        return " ".join(s.strip() for s in keys.get(k, []) if s.strip())

    def items(k, limit=6):
        out, buf = [], None
        for s in keys.get(k, []):
            if re.match(r"^\s{0,4}-\s", s):
                if buf:
                    out.append(buf)
                buf = re.sub(r"^\s*-\s+", "", s).strip()
            elif buf is not None and s.strip():
                buf += " " + s.strip()
        if buf:
            out.append(buf)
        return out[:limit]

    return {
        "file": path.name,
        "timestamp": scalar("timestamp"),
        "branch": scalar("branch")[:160],
        "summary": scalar("summary"),
        "next_steps": items("next_steps"),
    }


def newest_wrapup(repo):
    d = repo / "tmp" / "wrapups"
    if not d.is_dir():
        return None
    files = sorted(p for p in d.iterdir() if p.suffix in (".yaml", ".yml"))
    return parse_wrapup(files[-1]) if files else None


def open_prs(remote):
    try:
        out = subprocess.run(["gh", "pr", "list", "-R", remote, "--json", "number,title,headRefName,updatedAt", "--limit", "20"],
                             capture_output=True, text=True, timeout=30).stdout
        return json.loads(out or "[]")
    except Exception:
        return []


def profile(repo, since, want_prs):
    p = {"name": repo.name, "git": (repo / ".git").exists()}
    if not p["git"]:
        return p
    p["branch"] = git(repo, "symbolic-ref", "--short", "-q", "HEAD") or "(detached/empty)"
    p["last"] = git(repo, "log", "-1", "--format=%ad", "--date=short") or "-"
    p["commits"] = git(repo, "rev-list", "--count", "HEAD") or "0"
    p["dirty"] = len([l for l in git(repo, "status", "--porcelain").splitlines() if l])
    up = git(repo, "rev-list", "--count", "@{u}..HEAD")
    p["unpushed"] = int(up) if up.isdigit() else None
    p["remote"] = re.sub(r"\.git$", "", re.sub(r".*github\.com[:/]", "", git(repo, "remote", "get-url", "origin")))
    p["new_commits"] = []
    if since:
        log = git(repo, "log", "--all", f"--since={since}", "--format=%h %ad %s", "--date=short")
        p["new_commits"] = log.splitlines()[:15]
    p["wrapup"] = newest_wrapup(repo)
    p["wrapup_new"] = bool(since and p["wrapup"] and p["wrapup"]["timestamp"] > since)
    p["prs"] = open_prs(p["remote"]) if (want_prs and p["remote"]) else []
    return p


def render(profiles, since, now, order):
    L = []
    L.append(f"# STATUS — generated by scripts/sync.py at {now}")
    L.append(f"_Previous sync: {since or 'never'}. Do not hand-edit; rerun `scripts/sync.py --write`._\n")

    moved = [p for p in profiles if p.get("git") and (p["new_commits"] or p["wrapup_new"] or p["dirty"] or p["unpushed"])]
    L.append("## Delta since last sync")
    if not moved:
        L.append("Nothing moved.\n")
    for p in moved:
        rank, ho = order.get(p["name"], (None, False))
        tag = f"#{rank}" if rank else "unranked"
        tag += " HANDS-OFF" if ho else ""
        flags = []
        if p["new_commits"]:
            flags.append(f"{len(p['new_commits'])} new commit(s)")
        if p["wrapup_new"]:
            flags.append("new wrapup")
        if p["dirty"]:
            flags.append(f"{p['dirty']} dirty file(s)")
        if p["unpushed"]:
            flags.append(f"{p['unpushed']} unpushed")
        L.append(f"### {p['name']} ({tag}) — {', '.join(flags)}")
        for c in p["new_commits"][:8]:
            L.append(f"- `{c}`")
        if p["wrapup_new"] and p["wrapup"]:
            L.append(f"- wrapup `{p['wrapup']['file']}`: {p['wrapup']['summary'][:300]}")
        L.append("")

    L.append("## All repos (priority order, then unranked)")
    L.append("| # | repo | branch | last commit | commits | dirty | unpushed | newest wrapup | open PRs |")
    L.append("|---|---|---|---|---|---|---|---|---|")
    for p in profiles:
        rank, ho = order.get(p["name"], (None, False))
        r = f"{rank}{' 🚫' if ho else ''}" if rank else "–"
        if not p.get("git"):
            L.append(f"| {r} | {p['name']} | (no git) | | | | | | |")
            continue
        w = p["wrapup"]["file"] if p["wrapup"] else "–"
        prs = ", ".join(f"#{x['number']}" for x in p["prs"]) or ("–" if p["prs"] == [] else "?")
        L.append(f"| {r} | {p['name']} | {p['branch']} | {p['last']} | {p['commits']} | {p['dirty']} | {p['unpushed'] if p['unpushed'] is not None else '?'} | {w} | {prs} |")
    L.append("\n🚫 = HANDS-OFF (user drives it personally; don't edit from here).\n")

    L.append("## Newest wrapup per repo (next_steps as written there)")
    for p in profiles:
        w = p.get("wrapup")
        if not w:
            continue
        L.append(f"### {p['name']} — `{w['file']}` ({w['timestamp']})")
        if w["branch"]:
            L.append(f"- branch: {w['branch']}")
        if w["summary"]:
            L.append(f"- summary: {w['summary'][:600]}")
        for i, s in enumerate(w["next_steps"], 1):
            L.append(f"  {i}. {s[:220]}")
        L.append("")
    return "\n".join(L)


def write_data(profiles, now, since):
    """docs/data.json for the dashboard + state/history.json (percent over time)."""
    proj = load_projects()
    hist = json.loads(HISTORY.read_text()) if HISTORY.exists() else {}
    today = now[:10]
    repos = []
    for p in profiles:
        j = proj.get(p["name"], {})
        h = hist.setdefault(p["name"], [])
        if "percent" in j and (not h or h[-1]["date"] != today):
            h.append({"date": today, "percent": j["percent"]})
        elif h and "percent" in j:
            h[-1]["percent"] = j["percent"]
        repos.append({
            "name": p["name"], "rank": j.get("rank"), "hands_off": bool(j.get("hands_off")),
            "goal": j.get("goal", ""), "target": j.get("target", ""), "live": j.get("live", ""),
            "percent": j.get("percent"), "eta_days": j.get("eta_days"),
            "remaining": j.get("remaining", []), "blocked_on_user": j.get("blocked_on_user", []),
            "estimates": j.get("estimates", []), "note": j.get("note", ""),
            "plan": f"projects/{p['name']}.md",
            "git": {k: p.get(k) for k in ("branch", "last", "commits", "dirty", "unpushed", "remote")} if p.get("git") else None,
            "new_commits": p.get("new_commits", []),
            "wrapup": ({"file": p["wrapup"]["file"], "timestamp": p["wrapup"]["timestamp"],
                        "summary": p["wrapup"]["summary"][:400], "next_steps": p["wrapup"]["next_steps"][:4]}
                       if p.get("wrapup") else None),
            "prs": p.get("prs", []),
            "history": h,
        })
    # calibration ledger across all repos
    done = [dict(e, repo=r["name"]) for r in repos for e in r["estimates"] if e.get("done") and e.get("actual_days")]
    est_sum = sum(e["est_days"] for e in done) or 0
    act_sum = sum(e["actual_days"] for e in done) or 0
    calib = {"completed": len(done), "est_days": est_sum, "actual_days": act_sum,
             "slip_factor": round(act_sum / est_sum, 2) if est_sum else None}
    DATA.parent.mkdir(exist_ok=True)
    DATA.write_text(json.dumps({"generated_at": now, "previous_sync": since, "calibration": calib, "repos": repos}, indent=1) + "\n")
    HISTORY.write_text(json.dumps(hist, indent=1) + "\n")


def render_priorities(now):
    proj = load_projects()
    ranked = sorted([(v.get("rank") or 999, k, v) for k, v in proj.items()])
    L = [f"# PRIORITIES — generated from `state/projects.json` at {now[:16]}",
         "_Edit `state/projects.json` (rank, hands_off, percent, eta_days, remaining, estimates), then `scripts/sync.py --write`. Prose plans live in `projects/<repo>.md`._", ""]
    L.append("## Ranked")
    for rank, k, v in ranked:
        if rank == 999:
            continue
        ho = " — **HANDS-OFF** (user drives it personally; do not edit from here unless told in-session)" if v.get("hands_off") else ""
        eta = f", ETA ~{v['eta_days']} agent-days" if v.get("eta_days") else ""
        L.append(f"{rank}. **{k}**{ho} — {v.get('percent', '?')}%{eta}")
        L.append(f"   - goal: {v.get('goal', '')}")
        L.append(f"   - shipped means: see `projects/{k}.md`")
        for r in v.get("remaining", [])[:5]:
            L.append(f"   - [ ] {r}")
        if v.get("blocked_on_user"):
            L.append(f"   - needs user: {'; '.join(v['blocked_on_user'])}")
        L.append("")
    L.append("## Unranked (live or parked; touch only when asked)")
    L.append("| repo | % | live | goal |")
    L.append("|---|---|---|---|")
    for rank, k, v in ranked:
        if rank != 999:
            continue
        L.append(f"| {k} | {v.get('percent', '?')} | {v.get('live', '')} | {v.get('goal', '')} |")
    L.append("")
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--prs", action="store_true")
    ap.add_argument("--repo")
    a = ap.parse_args()

    since = STAMP.read_text().strip() if STAMP.exists() else ""
    now = dt.datetime.now().astimezone().replace(microsecond=0).isoformat()
    order = priority_order()
    repos = [d for d in sorted(ROOT.iterdir(), key=lambda x: x.name.lower()) if d.is_dir() and d.name != SELF and not d.name.startswith(".")]
    if a.repo:
        repos = [d for d in repos if d.name == a.repo]
    profiles = [profile(r, since, a.prs) for r in repos]
    profiles.sort(key=lambda p: (order.get(p["name"], (999, False))[0], p["name"].lower()))
    out = render(profiles, since, now, order)
    print(out)
    if a.write:
        STATUS.write_text(out + "\n")
        write_data(profiles, now, since)
        PRIORITIES.write_text(render_priorities(now))
        STAMP.parent.mkdir(exist_ok=True)
        STAMP.write_text(now + "\n")
        print(f"\n[wrote {STATUS.name}, stamped {now}]", file=sys.stderr)


if __name__ == "__main__":
    main()
